---
- hosts: workstation

  tasks:
    - name: print from playbook
      debug: msg="in playbooks/playbook.yml"

    - name: easy install pip
      easy_install: name=pip
      sudo: yes

    - name: install apps from pip
      pip: name={{item}}
      sudo: yes
      with_items:
          - virtualenv
          - cliff
          - pyyaml
          - awscli

    - name: install apps from homebrew
      homebrew: name={{item}} state=present
      with_items:
          - coreutils
          - git
          - node
          - maven
          - rbenv
          - dos2unix
          - ruby
          - wget
          - ctags

    # requires node/npm from above
    - name: install global apps from npm
      npm: name={{item}} global=yes
      with_items:
          - grunt-cli

    - name: create homdir symlinks
      file: src={{item.from}} dest={{item.to}} state=link
      sudo: no
      with_items:
         - from: ~/Dropbox/mac/battleschool
           to: ~/.battleschool
         - from: ~/Dropbox/mac/.ctags
           to: ~/.ctags
         - from: ~/Dropbox/mac/.gitconfig
           to: ~/.gitconfig
         - from: ~/Dropbox/mac/.inputrc
           to: ~/.inputrc
         - from: ~/Dropbox/mac/.profile
           to: ~/.profile
         - from: ~/Dropbox/mac/.todo
           to: ~/.todo
         - from: ~/Dropbox/mac/.vimrc
           to: ~/.vimrc
         - from: ~/Dropbox/mac/.zsh
           to: ~/.zsh
         - from: ~/Dropbox/mac/.zshrc
           to: ~/.zshrc
         - from: ~/Dropbox/mac/bin
           to: ~/bin
         - from: ~/Google\ Drive
           to: ~/drive

         

#    - name: install gems
#      gem: name={{item}} state=latest
#      with_items:
#          - brewbygems
#          - bundler
#          - compass
